script_data = [
   {
      "author_name" : "!WAHa_06x36",
      "author_url" : "https://wakaba.c3.cx",
      "download_url" : "https://wakaba.c3.cx/releases/Kareha/",
      "language" : "Perl",
      "name" : "Kareha",
      "notes" : "This is my favourite script. It is easy for beginners to modify and it runs well on low-end servers. Kareha is spiritually similar to Wakaba as it is written by the same author. It is very popular in textboard communities such as 4-ch.net and sageru.org",
      "version" : "3.1.4",
      "status" : "stable",
      "last_checked" : "2019-11-23",
      "created" : "2004?"
   },
   {
      "author_name" : "Ben Bitdiddle",
      "author_url" : "https://gitlab.com/naughtybits",
      "download_url" : "https://gitlab.com/naughtybits/schemebbs",
      "language" : "MIT Scheme",
      "name" : "SchemeBBS",
      "notes" : "SchemeBBS powers textboard.org, it features typical kareha-style textboard features such as quoting and shiichan-style text formatting. The code itself has few dependencies and is written competently but may be too lightweight for some people.",
      "version" : "n/a",
      "status" : "stable",
      "last_checked" : "2019-11-23",
      "created" : "2018"
   },
   {
      "author_name" : "Yumi",
      "author_url" : "https://bm.howler.space/yumi/",
      "download_url" : "https://github.com/yumi-xx/RAL",
      "language" : "PHP",
      "name" : "RAL",
      "notes" : "RAL was written specifically for howler.space and attempts to focus on so-called perpetual posting (documented as ``continuities'') with a grid-style interface for viewing threads.",
      "version" : "v3.1",
      "status" : "stable",
      "last_checked" : "2019-11-23",
      "created" : "2017"
   },
   {
      "author_name" : "majestrate",
      "author_url" : "https://github.com/majestrate",
      "download_url" : "https://github.com/majestrate/nntpchan/releases",
      "language" : "Go",
      "name" : "nntpchan",
      "notes" : "The main feature of NNTPChan is that it uses the NNTP protocol to assist in decentralising the board data. To participate in posting, you must have permission to access a server within the graph or use a web client. For a while (between 2014-2018) it was popular, however as of 2019 it appears there are no web-accessible boards anymore.",
      "version" : "3.1.0",
      "status" : "maintained",
      "last_checked" : "2019-11-26",
      "created" : "2015"
   },
   {
      "author_name" : "Kyle Farwell",
      "author_url" : "http://kfarwell.org",
      "download_url" : "https://github.com/kfarwell/werchan",
      "language" : "Plan 9 rc",
      "name" : "werchan",
      "notes" : "the chan fell off. Probably a great choice if you run Plan 9 or want to use an almost CGI-free environment (!).",
      "version" : "1.5",
      "status" : "stable",
      "last_checked" : "2019-11-26",
      "created" : "2015"
   },
   {
      "author_name" : "!WAHa_06x36",
      "author_url" : "http://wakaba.c3.cx",
      "download_url" : "http://wakaba.c3.cx",
      "language" : "Perl",
      "name" : "Wakaba",
      "notes" : "Wakaba is a very old and popular script (slightly more popular than its cousin, Kareha) derived from Futallaby code. Wakaba uses a MySQL backend for storage. Wakaba's design serves as the scaffolding for many other scripts.",
      "version" : "3.0.9",
      "status" : "stable",
      "last_checked" : "2019-11-23",
      "created" : "2004"
   },
   {
      "author_name" : "tslocum",
      "author_url" : "http://kusabax.cultnet.net",
      "download_url" : "http://kusabax.cultnet.net",
      "language" : "PHP",
      "name" : "Kusaba",
      "notes" : "Kusaba was once the most popular script for imageboards. Kusaba's history is tumultuous and colourful since it was the target of many hacking attempts partly due to the code quality and partly due to the types of communities which used it. The original author (Trevor) abandoned it in 2008 and Harrison Weston became the new maintainer.",
      "version" : "0.9.3",
      "status" : "stable",
      "last_checked" : "2019-11-26",
      "created" : "2008?"
   },
   {
      "author_name" : "Stephen Lynx",
      "author_url" : "http://gitgud.io/LynxChan",
      "download_url" : "https://gitgud.io/LynxChan/LynxChan/tags",
      "language" : "nodejs",
      "name" : "LynxChan",
      "notes" : "Over the years LynxChan has evolved into a fully-fledged imageboard engine with a well-designed plugin system. The project is a one-man effort by Stephen Lynx. It is somewhat popular, currently being used by at least 20 websites.",
      "version" : "2.2.17",
      "status" : "maintained",
      "last_checked" : "2019-08-11",
      "created" : "2015"
   },
   {
      "author_name" : "Kermit Alexander II",
      "author_url" : "https://github.com/DangerOnTheRanger/",
      "download_url" : "https://github.com/DangerOnTheRanger/maniwani",
      "language" : "Python",
      "name" : "maniwani",
      "notes" : "Experimental BBS with modern ideologies.",
      "version" : "52ca059",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Yamada",
      "author_url" : "http://iloveyamada.org",
      "download_url" : "#none",
      "language" : "PHP",
      "name" : "Yamada IB",
      "notes" : "A long time ago the author sent me the source, unfortunately I have not retained it over the years. It is a fork of TinyIB.",
      "version" : "n/a",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Joshua Moore",
      "author_url" : "https://github.com/joshiemoore",
      "download_url" : "https://github.com/joshiemoore/NodeChan",
      "language" : "Java",
      "name" : "NodeChan",
      "notes" : "ambitious attempt at p2p which does not use the DHT",
      "version" : "0.7.5",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "steenuil",
      "author_url" : "https://github.com/steinuil",
      "download_url" : "https://github.com/steinuil/negoto",
      "language" : "Ur",
      "name" : "negoto",
      "notes" : "runs as an executable",
      "version" : "05d87bb",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Ernstchan",
      "author_url" : "http://kfarwell.org",
      "download_url" : "https://github.com/ernstchan/phutaba",
      "language" : "Perl",
      "name" : "Phutaba",
      "notes" : "lots of small new features",
      "version" : "f0356b9",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "\"josh\"",
      "author_url" : "#none",
      "download_url" : "https://github.com/infinity-next/infinity-next",
      "language" : "PHP",
      "name" : "Infinity Next",
      "notes" : "",
      "version" : "08/11/19 (git)",
      "status" : "maintained",
      "last_checked" : "2019-08-11",
      "created" : "2015"
   },
   {
      "author_name" : "oprel",
      "author_url" : "https://github.com/oprel",
      "download_url" : "https://github.com/oprel/emanon",
      "language" : "Perl",
      "name" : "emanon",
      "notes" : "modern extensions to Tablecat",
      "version" : "727486f",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "flashwave",
      "author_url" : "http://flash.moe/",
      "download_url" : "https://github.com/flashwave/satoko",
      "language" : "PHP",
      "name" : "Satoko",
      "notes" : "work in progress",
      "version" : "5aca872",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "ahushh",
      "author_url" : "https://github.com/ahushh/",
      "download_url" : "https://github.com/ahushh/Monaba",
      "language" : "Haskell",
      "name" : "Monaba",
      "notes" : "lots of modern features",
      "version" : "5d44e8d",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "czaks",
      "author_url" : "https://github.com/czaks",
      "download_url" : "https://github.com/vichan-devel/vichan/releases",
      "language" : "PHP",
      "name" : "vichan",
      "notes" : "vroom vroom caching",
      "version" : "5.1.0",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "bakape",
      "author_url" : "https://github.com/bakape",
      "download_url" : "https://github.com/bakape/meguca/releases",
      "language" : "Go",
      "name" : "meguca",
      "notes" : "where do we go from here?",
      "version" : "2.3.0",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "mission712",
      "author_url" : "https://github.com/mission712",
      "download_url" : "https://github.com/mission712/blazechan",
      "language" : "PHP",
      "name" : "BlazeChan",
      "notes" : "WIP, looks dead",
      "version" : "54a941f",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "k-anon",
      "author_url" : "http://git.kiace.com.ar/",
      "download_url" : "https://github.com/dequis/wakarimasen/releases",
      "language" : "Python",
      "name" : "wakarimasen",
      "notes" : "wakaba-compatible, low memory usage, extended admin panel",
      "version" : "rev 444",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "marlencrabapple",
      "author_url" : "https://github.com/marlencrabapple/",
      "download_url" : "https://github.com/marlencrabapple/Glaukaba",
      "language" : "Perl",
      "name" : "Glaukaba",
      "notes" : "wakaba fork with a lot of new changes",
      "version" : "0.125",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Desuneko",
      "author_url" : "#none",
      "download_url" : "https://github.com/MitsubaBBS/Mitsuba",
      "language" : "PHP",
      "name" : "Mitsuba",
      "notes" : "made from scratch, has a module system",
      "version" : "rev 762",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "thatdog",
      "author_url" : "http://www.1chan.net/futallaby/",
      "download_url" : "http://www.1chan.net/futallaby/",
      "language" : "PHP",
      "name" : "Futallaby",
      "notes" : "Futallaby is historically important, serving as the original codebase for 4chan.org. It is derived heavily from Futaba. Futallaby inspired many other scripts such as Kusaba, TinyIB, Tinyboard, TinyBB, etc.",
      "version" : "040103",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "2003"
   },
   {
      "author_name" : "Futaba Channel",
      "author_url" : "https://www.2chan.net/",
      "download_url" : "https://www.2chan.net/script/",
      "language" : "PHP",
      "name" : "Futaba",
      "notes" : "Futaba is the historical script written for 2chan.net which served as the spiritual basis for the vast majority of all other imageboard scripts. The significance of this script for the greater *chan community is understated.",
      "version" : "051031",
      "status" : "stable",
      "last_checked" : "2019-11-26",
      "created" : "2001"
   },
   {
      "author_name" : "Floens",
      "author_url" : "https://github.com/Floens",
      "download_url" : "https://github.com/Floens/uchan",
      "language" : "Python",
      "name" : "μchan",
      "notes" : "Focus on separation of concerns.",
      "version" : "n/a",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "emgram769",
      "author_url" : "https://github.com/emgram769",
      "download_url" : "https://github.com/emgram769/live4chan",
      "language" : "node.js",
      "name" : "livechan",
      "notes" : "self-styled \"IRC-like imageboard\"",
      "version" : "n/a",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Lal'C",
      "author_url" : "http://doushio.com/",
      "download_url" : "https://github.com/lalcmellkmal/doushio",
      "language" : "node.js",
      "name" : "Doushio",
      "notes" : "uses Redis as a datastore",
      "version" : "rev 1.465",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "woxxy",
      "author_url" : "https://github.com/woxxy",
      "download_url" : "https://github.com/FoolCode/FoolFuuka",
      "language" : "PHP",
      "name" : "FoolFuuka",
      "notes" : "made for archiving *boards, very fast",
      "version" : "0.730",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Tanami",
      "author_url" : "http:/9ch.in",
      "download_url" : "#none",
      "language" : "Perl",
      "name" : "Macro",
      "notes" : "A script that I wrote in a weekend, largely inspired by Kareha. I ran it on 9ch.in for a while but now it is unmaintained.",
      "version" : "0.5.1",
      "status" : "unmaintained",
      "last_checked" : "2019-11-23",
      "created" : "2008"
   },
   {
      "author_name" : "Albright",
      "author_url" : "mailto:taqsuqs@gmail.com",
      "download_url" : "http://code.google.com/p/drydock/",
      "language" : "PHP",
      "name" : "Drydock",
      "notes" : "Drydock was a multi-board imageboard script which featurs a complete administration interface, similar to Kusaba. It was one of the first scripts to include a blotter function and image capcodes. The author appears to have stopped development since mid-2013. It was previously being used as the backend for kchan (url unknown).",
      "version" : "r291",
      "status" : "discontinued",
      "last_checked" : "2019-11-26",
      "created" : "2008"
   },
   {
      "author_name" : "sabitsuki",
      "author_url" : "http://4x13.net/",
      "download_url" : "https://github.com/153/iyagi-bbs/",
      "language" : "Python",
      "name" : "iyagi",
      "notes" : "new clone of tablecat's backend",
      "version" : "4b4e080",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Vladimir37",
      "author_url" : "http://github.com/Vladimir37",
      "download_url" : "https://github.com/Vladimir37/Hanako/",
      "language" : "node.js",
      "name" : "Hanako",
      "notes" : "strong focus on scalability",
      "version" : "1.0.0",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Gareth Smith",
      "author_url" : "http://spacetaken.net/",
      "download_url" : "http://spacetaken.net/img2/",
      "language" : "PHP",
      "name" : "img2",
      "notes" : "untested",
      "version" : "061610",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Matthew Trevino",
      "author_url" : "https://github.com/matthew-trevino",
      "download_url" : "https://github.com/matthew-trevino/regularboard",
      "language" : "PHP",
      "name" : "Regular Board",
      "notes" : "channel-style filtering, forum-like layout",
      "version" : "9528cce",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Shii",
      "author_url" : "http://www.shii.org",
      "download_url" : "http://wakaba.c3.cx/shii/shiichan",
      "language" : "PHP",
      "name" : "Shiichan",
      "notes" : "use Kareha instead",
      "version" : "3960",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "thewiz",
      "author_url" : "#none",
      "download_url" : "https://bitbucket.org/thewiz/gibson-bbs/overview",
      "language" : "node.js",
      "name" : "gibson",
      "notes" : "emulates pre-internet BBSen with a JS console",
      "version" : "1.30",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "hotaru2k3",
      "author_url" : "http://hotaru.thinkindifferent.net/",
      "download_url" : "https://github.com/hotaru2k3/",
      "language" : "Perl",
      "name" : "TinyBB",
      "notes" : "there is TinyBB &amp; TinyBBv3",
      "version" : "???",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "``maiko''",
      "author_url" : "http://tablecat.co.cc",
      "download_url" : "http://tablecat.co.cc/bbs/",
      "language" : "Perl",
      "name" : "Tablecat",
      "notes" : "VIP",
      "version" : "240411",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "???",
      "author_url" : "http://siokara.que.jp/",
      "download_url" : "http://siokara.que.jp/",
      "language" : "PHP",
      "name" : "Siokara",
      "notes" : "not updated since 2004",
      "version" : "1.04a",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "tslocum",
      "author_url" : "https://github.com/tslocum/",
      "download_url" : "https://github.com/tslocum/PyIB-Standalone",
      "language" : "Python",
      "name" : "PyIB",
      "notes" : "PyIB was originally written for PAQ.CC, an invite-only imageboard which used a system of referral tokens. Unfortunately the available source-code does not include this feature. The author appeared to stop development shortly after PAQ.CC went down.",
      "version" : "r66",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "???",
      "author_url" : "http://yui-cynthia-bne-jp.cocolog-nifty.com/blog/",
      "download_url" : "http://yui-cynthia-bne-jp.cocolog-nifty.com/blog/",
      "language" : "PHP",
      "name" : "Cynthia",
      "notes" : "japanese",
      "version" : "02e1",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "sparky4+4",
      "author_url" : "http://4ch.irc.su",
      "download_url" : "http://4ch.irc.su/",
      "language" : "PHP",
      "name" : "Yotsubanome",
      "notes" : "written by a retard",
      "version" : "who cares",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "tj9991",
      "author_url" : "#none",
      "download_url" : "http://www.ohloh.net/p/tinyib",
      "language" : "PHP",
      "name" : "TinyIB",
      "notes" : "never seen it being used",
      "version" : "???",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "kent-web",
      "author_url" : "http://www.kent-web.com",
      "download_url" : "http://www.kent-web.com/bbs/joyful.html",
      "language" : "PHP",
      "name" : "Joyful Note",
      "notes" : "japanese, untested",
      "version" : "2.73",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "ochiba",
      "author_url" : "http://ochiba.x-maru.org/",
      "download_url" : "http://ochiba.x-maru.org/",
      "language" : "PHP",
      "name" : "Ochiba",
      "notes" : "Ochiba was created out of the author's desire for a hybrid bbs script which allowed for imageboard-style commenting on top of a photo-blogging interface. It also supports RSS feeds, multiple-file uploads, and a keyword system for filtering.",
      "version" : "1.2.1",
      "status" : "stable",
      "last_checked" : "2019-11-26",
      "created" : "2004"
   },
   {
      "author_name" : "bottiger",
      "author_url" : "mailto:bottiger@?gee-mail?.com",
      "download_url" : "http://code.google.com/p/4chandk/downloads/list",
      "language" : "PHP",
      "name" : "4chandk",
      "notes" : "appears to be dead.",
      "version" : "240207",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "various",
      "author_url" : "#none",
      "download_url" : "http://pixmicat.openfoundry.org/",
      "language" : "PHP",
      "name" : "Pixmicat",
      "notes" : "taiwanese script based on japanese source",
      "version" : "6",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "???",
      "author_url" : "http://www12.atwiki.jp/0ch/",
      "download_url" : "files/0ch_test070124.zip",
      "language" : "",
      "name" : "0ch",
      "notes" : "untested",
      "version" : "4.xx",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "???",
      "author_url" : "http://php.s3.to/",
      "download_url" : "http://php.s3.to/",
      "language" : "PHP",
      "name" : "GazouBBS",
      "notes" : "ancient",
      "version" : "???",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "???",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "PHP?",
      "name" : "Gazo-CH",
      "notes" : "this might be an alias for GazouBBS",
      "version" : "???",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "team4chan",
      "author_url" : "http://4chan.org/team",
      "download_url" : "files/yotsuba.txt",
      "language" : "PHP",
      "name" : "Yotsuba",
      "notes" : "Yotsuba was written by team4chan for 4chan.org. It originally drew heavily from Futallaby's codebase but is now most likely using more ``scalable'' PHP practices. The download link is for an older leaked copy of the board rendering component.",
      "version" : "closed-source",
      "status" : "maintained",
      "last_checked" : "2019-08-11",
      "created" : "2003"
   },
   {
      "author_name" : "Cudder",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "PHP",
      "name" : "REchan",
      "notes" : "REchan was written by a famous /prog/ shitposter for rechan.eu.org, it has a similar appearance to Kusaba X but evidence from archive.org suggests that it was written from scratch. Unfortunately there is no publicly-available source code since the main website went down.",
      "version" : "080726 (r4)",
      "status" : "unmaintained",
      "last_checked" : "2019-08-11",
      "created" : "2008"
   },
   {
      "author_name" : "SYNchan",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "PHP",
      "name" : "Mikich",
      "notes" : "SYNchan's script",
      "version" : "???",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "savetheinternet",
      "author_url" : "https://github.com/savetheinternet",
      "download_url" : "https://github.com/savetheinternet/Tinyboard",
      "language" : "PHP",
      "name" : "Tinyboard",
      "notes" : "Originally written for 4chon.net, Tinyboard was the first imageboard to utilise DNSBL filtering and make use of modern PHP practices, such as using APC for caching. The codebase has been used as the basis for other projects such as vichan.",
      "version" : "0.9.2",
      "status" : "stable",
      "last_checked" : "2019-08-11",
      "created" : "2010"
   },
   {
      "author_name" : "kirtaner",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "Perl",
      "name" : "Taimaba",
      "notes" : "420chan's script",
      "version" : "???",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Storlek",
      "author_url" : "http://j.rigelseven.com/",
      "download_url" : "https://github.com/Storlek/matsuba",
      "language" : "PHP?",
      "name" : "Matsuba",
      "notes" : "sovietrussia's script",
      "version" : "<i>(git)</i>",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Wajett Systems",
      "author_url" : "http://www.wajett.net",
      "download_url" : "http://www.wajett.net/labs/cb_02.php",
      "language" : "???",
      "name" : "C-BOARD",
      "notes" : "this is actually a modded version",
      "version" : "3.8",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "unknown",
      "author_url" : "#none",
      "download_url" : "files/kb19ful.lzh",
      "language" : "Perl",
      "name" : "K-Board",
      "notes" : "experimental features",
      "version" : "1.9",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Tacky",
      "author_url" : "#none",
      "download_url" : "http://tackysroom.com/cgi/cgi_tackynote.htm",
      "language" : "Perl",
      "name" : "Tackynote",
      "notes" : "untested",
      "version" : "0.996",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Tacky",
      "author_url" : "#none",
      "download_url" : "http://tackysroom.com/cgi/cgi_mkakikomitai2.htm",
      "language" : "Perl",
      "name" : "Mkakikomitai",
      "notes" : "japanese, emoticons and shit",
      "version" : "0.73",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Tacky",
      "author_url" : "http://tackysroom.com",
      "download_url" : "http://tackysroom.com/cgi/cgi_tackyvote.htm",
      "language" : "Perl",
      "name" : "Tackyvote",
      "notes" : "",
      "version" : "0.95",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Tacky",
      "author_url" : "http://tackysroom.com/",
      "download_url" : "http://tackysroom.com/cgi/cgi_mezase2.htm",
      "language" : "Perl",
      "name" : "Mezase2",
      "notes" : "",
      "version" : "0.58",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "iignotus",
      "author_url" : "http://sourceforge.net/projects/ignium/",
      "download_url" : "http://sourceforge.net/projects/ignium/",
      "language" : "PHP",
      "name" : "Ignium",
      "notes" : "untested, website is horrid",
      "version" : "170709",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Federico Ramirez",
      "author_url" : "http://code.google.com/p/hachan/",
      "download_url" : "http://code.google.com/p/hachan/",
      "language" : "PHP",
      "name" : "Ha Chan",
      "notes" : "not actively developed?",
      "version" : "1.07",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "tehHedger",
      "author_url" : "http://orphereus.anoma.ch",
      "download_url" : "http://orphereus.anoma.ch/",
      "language" : "Python",
      "name" : "Orphereus",
      "notes" : "python, \"modular\"",
      "version" : "???",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "k-anon",
      "author_url" : "http://git.kiace.com.ar/",
      "download_url" : "https://suigintou.weedy.ca/trac/desuchan/browser/trunk",
      "language" : "Perl",
      "name" : "desuchan",
      "notes" : "forked from wakaba, lots of changes",
      "version" : "rev 168",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "unknown",
      "author_url" : "http://code.google.com/u/@VhRSQF1YAhZEXwZ1/",
      "download_url" : "http://code.google.com/p/ochan/",
      "language" : "Java",
      "name" : "ochan",
      "notes" : "ENTERPRISE QUALITY",
      "version" : "r326",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "airflow83",
      "author_url" : "#none",
      "download_url" : "http://code.google.com/p/kotoba-ib/",
      "language" : "PHP",
      "name" : "kotoba-ib",
      "notes" : "russian",
      "version" : "r437",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "to-ru",
      "author_url" : "#none",
      "download_url" : "files/imgboard.cgi.txt",
      "language" : "Perl",
      "name" : "imgboard.cgi",
      "notes" : "quite popular in japan",
      "version" : "1.22",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "CGI RESCUE",
      "author_url" : "http://www.rescue.ne.jp/",
      "download_url" : "http://www.rescue.ne.jp/cgi/minibbs1/",
      "language" : "Perl",
      "name" : "minibbs",
      "notes" : "japanese",
      "version" : "10.32",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "unknown",
      "author_url" : "http://www.sweetnote.com/",
      "download_url" : "http://www.sweetnote.com/",
      "language" : "unknown",
      "name" : "Sweetnote",
      "notes" : "proprietary?",
      "version" : "unknown",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "unknown",
      "author_url" : "#none",
      "download_url" : "http://sourceforge.jp/projects/sfnet_imageboard/",
      "language" : "",
      "name" : "imageboard",
      "notes" : "lol",
      "version" : "1.21",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "ivarch",
      "author_url" : "#none",
      "download_url" : "http://freshmeat.net/projects/mconv",
      "language" : "Perl",
      "name" : "mconv",
      "notes" : "last updated in 2004, archaic",
      "version" : "1.2.7",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "spoot",
      "author_url" : "mailto:spoot@saguaroimgboard.co.cc ",
      "download_url" : "http://saguaroimgboard.co.cc/download/",
      "language" : "PHP",
      "name" : "Saguaro",
      "notes" : "based on futallaby",
      "version" : "0.97.5",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "luza",
      "author_url" : "#none",
      "download_url" : "http://code.google.com/p/kakaha/",
      "language" : "PHP",
      "name" : "Kakaha",
      "notes" : "uses SQLite backend",
      "version" : "r21",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "unknown",
      "author_url" : "#none",
      "download_url" : "http://himgb.googlecode.com/svn/trunk/hImgb.hs",
      "language" : "Haskell",
      "name" : "himgb",
      "notes" : "U MENA HASKEL",
      "version" : "unknown",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "unknown",
      "author_url" : "#none",
      "download_url" : "http://code.google.com/p/backyardimgboard/",
      "language" : "PHP",
      "name" : "backyard",
      "notes" : "looks buggy",
      "version" : "0.0.5",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "tslocum",
      "author_url" : "#none",
      "download_url" : "http://code.google.com/p/p2pchan/",
      "language" : "python",
      "name" : "p2pchan",
      "notes" : "windows-only?",
      "version" : "???",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Albright",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "PHP",
      "name" : "Thorn",
      "notes" : "Thorn was the author's first attempt at making an imageboard, based on Wakaba. The author has requested that I do not provide sources or other information so this serves simply as a reference to the fact it existed and was used at some point.",
      "version" : "n/a",
      "status" : "discontinued",
      "last_checked" : "2019-11-26",
      "created" : "n/a"
   },
   {
      "author_name" : "grumpy",
      "author_url" : "http://63chan.org",
      "download_url" : "files/Anonsaba.zip",
      "language" : "PHP",
      "name" : "Anonsaba",
      "notes" : "Anonsaba is apparently back-doored, DO NOT USE",
      "version" : "0.1",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "z411",
      "author_url" : "https://omaera.org/notme",
      "download_url" : "https://github.com/z411/weabot",
      "language" : "Python",
      "name" : "weabot",
      "notes" : "based on PyIB with most of the Kusaba feature set",
      "version" : "0.7.2",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Yuto Ikeno",
      "author_url" : "mailto:k1@mewc.to",
      "download_url" : "files/mewbbsall.tar.gz",
      "language" : "C",
      "name" : "mewBBS",
      "notes" : "very, very old",
      "version" : "4.9",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Yuto Ikeno",
      "author_url" : "mailto:k1@mewc.to",
      "download_url" : "http://mewc.to/CGI/miniboard.html",
      "language" : "Perl",
      "name" : "miniboard",
      "notes" : "also very old (1997!)",
      "version" : "1.1",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "NekoArc",
      "author_url" : "http://www.nekoarcnetwork.com",
      "download_url" : "http://code.google.com/p/arcnet",
      "language" : "PHP",
      "name" : "arcNET",
      "notes" : "used on 4chon, 314chan and mikuchan ",
      "version" : "r32",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Kazer",
      "author_url" : "http://kazer.es",
      "download_url" : "http://sourceforge.net/projects/excelis/",
      "language" : "PHP",
      "name" : "Excelis",
      "notes" : "untested, has smilies and such",
      "version" : "1.6",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "unknown",
      "author_url" : "#none",
      "download_url" : "http://nelliel.com",
      "language" : "PHP",
      "name" : "Nelliel",
      "notes" : "looks to be a decent Futallaby rewrite",
      "version" : "v0.9b-r5",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Ikimashou (?)",
      "author_url" : "http://http://ikimashou.net",
      "download_url" : "http://svn.dasaku.net/listing.php?repname=naranai&",
      "language" : "PHP",
      "name" : "Naranai",
      "notes" : "danbooru-type image script",
      "version" : "r50",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Ere Whitehouse",
      "author_url" : "http://www.rateitstar.com",
      "download_url" : "http://www.rateitstar.com/software.php",
      "language" : "PHP",
      "name" : "NitPick",
      "notes" : "image-posting, unlimited thread length?",
      "version" : "unknown",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "hotaru2k3",
      "author_url" : "http://hotaru.thinkindifferent.net",
      "download_url" : "https://github.com/hotaru2k3/PerlHP-bbs",
      "language" : "Perl",
      "name" : "PerlHP-bbs",
      "notes" : "it's probably going to be better than kusaba.",
      "version" : "unknown",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "Qiming Zeng",
      "author_url" : "http://28chan.org",
      "download_url" : "http://code.google.com/p/lucidtea/",
      "language" : "PHP",
      "name" : "Lucid Tea",
      "notes" : "level of completion undetermined",
      "version" : "r3",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "treeofsephiroth?",
      "author_url" : "#none",
      "download_url" : "http://gitorious.org/shimonoseki",
      "language" : "PHP",
      "name" : "Shimonoseki",
      "notes" : "appears to be a bland Kusaba X rewrite (possibly insecure)",
      "version" : "48a7d5ca",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "n/a",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "n/a",
      "name" : "Hatoya",
      "notes" : "n/a",
      "version" : "n/a",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "n/a",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "Perl",
      "name" : "EZ TREE",
      "notes" : "",
      "version" : "",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "n/a",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "Perl",
      "name" : "pdfbook",
      "notes" : "",
      "version" : "",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "n/a",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "Perl",
      "name" : "sbbs",
      "notes" : "",
      "version" : "",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "n/a",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "Perl",
      "name" : "Petit BBS",
      "notes" : "",
      "version" : "",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "n/a",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "Perl",
      "name" : "banabo",
      "notes" : "",
      "version" : "",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "n/a",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "Perl",
      "name" : "koutei",
      "notes" : "",
      "version" : "",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created" : "unknown"
   },
   {
      "author_name" : "n/a",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "Perl",
      "name" : "afbbs",
      "notes" : "",
      "version" : "",
      "status" : "unknown",
      "last_checked" : "2019-08-11",
      "created": "unknown"
   },
   {
      "author_name" : "n/a",
      "author_url" : "#none",
      "download_url" : "#none",
      "language" : "PHP",
      "name" : "Hydrogen",
      "notes" : "",
      "version" : "",
      "status" : "unknown",
      "last_checked" : "2019-11-26",
      "created": "unknown"
   }
]
